# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIDefinitiva.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(906, 677)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("background-color: rgb(54, 52, 65);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.sfondotasti = QtWidgets.QFrame(self.frame_3)
        self.sfondotasti.setMinimumSize(QtCore.QSize(50, 0))
        self.sfondotasti.setMaximumSize(QtCore.QSize(0, 16777215))
        self.sfondotasti.setSizeIncrement(QtCore.QSize(0, 0))
        self.sfondotasti.setStyleSheet("Qframe{\n"
"  \n"
"    \n"
"    \n"
"    padding-left: 0px;\n"
"}\n"
"QPushButton:{\n"
"\n"
"\n"
"border-radius: 10px;\n"
"}")
        self.sfondotasti.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sfondotasti.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sfondotasti.setLineWidth(1)
        self.sfondotasti.setMidLineWidth(1)
        self.sfondotasti.setObjectName("sfondotasti")
        self.formLayout_5 = QtWidgets.QFormLayout(self.sfondotasti)
        self.formLayout_5.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setSpacing(0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.frame_9 = QtWidgets.QFrame(self.sfondotasti)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_9.setStyleSheet("QPushButton:{\n"
"border-radius: 0px;}\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setLineWidth(1)
        self.frame_9.setObjectName("frame_9")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame_9)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setSpacing(0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.module0 = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.module0.sizePolicy().hasHeightForWidth())
        self.module0.setSizePolicy(sizePolicy)
        self.module0.setMinimumSize(QtCore.QSize(140, 50))
        self.module0.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.module0.setFont(font)
        self.module0.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    background-color: rgb(86, 105, 108);\n"
"}\n"
"QPushButton{\n"
"    border-left:5px solid transparent;\n"
"    background-image: url(:/icons/icons/cil-home.png);\n"
"    background-position: center left;\n"
"    background-repeat: none;\n"
"    padding-left: 60px;\n"
"Text-align:left;\n"
"    font: 25 16pt \"Microsoft YaHei UI Light 2\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 00px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    border-left-width: 7px;\n"
"    border-style: solid;\n"
"    \n"
"    border-color: rgb(0, 85, 255);\n"
"}")
        self.module0.setCheckable(True)
        self.module0.setChecked(True)
        self.module0.setAutoExclusive(False)
        self.module0.setObjectName("module0")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.module0)
        self.moduletest = QtWidgets.QPushButton(self.frame_9)
        self.moduletest.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moduletest.sizePolicy().hasHeightForWidth())
        self.moduletest.setSizePolicy(sizePolicy)
        self.moduletest.setMinimumSize(QtCore.QSize(140, 50))
        self.moduletest.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.moduletest.setFont(font)
        self.moduletest.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    background-color: rgb(86, 105, 108);\n"
"}\n"
"QPushButton{\n"
"    border-left:5px solid transparent;\n"
"    Text-align:left;\n"
"    background-image: url(:/icons/icons/cil-chevron-bottom.png);\n"
"    background-position: center left;\n"
"    background-repeat: none;\n"
"    padding-left: 60px;\n"
"    font: 25 16pt \"Microsoft YaHei UI Light 2\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 0px;\n"
"}\n"
"\n"
"\n"
"QPushButton:checked{\n"
"    border-left-width: 7px;\n"
"    border-style: solid;\n"
"    \n"
"    border-color: rgb(0, 85, 255);\n"
"}")
        self.moduletest.setCheckable(True)
        self.moduletest.setAutoExclusive(False)
        self.moduletest.setObjectName("moduletest")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.moduletest)
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.frame_9)
        self.moviment = QtWidgets.QFrame(self.sfondotasti)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moviment.sizePolicy().hasHeightForWidth())
        self.moviment.setSizePolicy(sizePolicy)
        self.moviment.setMinimumSize(QtCore.QSize(40, 0))
        self.moviment.setMaximumSize(QtCore.QSize(16777215, 0))
        self.moviment.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.moviment.setStyleSheet("QFrame{\n"
"    background-color: rgb(0,0,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(0, 163, 163);\n"
"}\n"
"QPushButton{\n"
"Text-align:left;\n"
"font: 25 18pt \"Microsoft YaHei UI Light \";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0,0,0);\n"
"padding-left: 10px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    border-left-width: 7px;\n"
"    border-style: solid;\n"
"    \n"
"    border-color: rgb(0, 163, 163);\n"
"}")
        self.moviment.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.moviment.setFrameShadow(QtWidgets.QFrame.Raised)
        self.moviment.setObjectName("moviment")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.moviment)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.module1 = QtWidgets.QPushButton(self.moviment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.module1.sizePolicy().hasHeightForWidth())
        self.module1.setSizePolicy(sizePolicy)
        self.module1.setMinimumSize(QtCore.QSize(140, 0))
        self.module1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light ")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.module1.setFont(font)
        self.module1.setStyleSheet("")
        self.module1.setCheckable(True)
        self.module1.setAutoExclusive(True)
        self.module1.setFlat(False)
        self.module1.setObjectName("module1")
        self.verticalLayout.addWidget(self.module1)
        self.module2 = QtWidgets.QPushButton(self.moviment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.module2.sizePolicy().hasHeightForWidth())
        self.module2.setSizePolicy(sizePolicy)
        self.module2.setMinimumSize(QtCore.QSize(140, 0))
        self.module2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light ")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.module2.setFont(font)
        self.module2.setStyleSheet("")
        self.module2.setCheckable(True)
        self.module2.setAutoExclusive(True)
        self.module2.setFlat(False)
        self.module2.setObjectName("module2")
        self.verticalLayout.addWidget(self.module2)
        self.module3 = QtWidgets.QPushButton(self.moviment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.module3.sizePolicy().hasHeightForWidth())
        self.module3.setSizePolicy(sizePolicy)
        self.module3.setMinimumSize(QtCore.QSize(140, 0))
        self.module3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light ")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.module3.setFont(font)
        self.module3.setStyleSheet("")
        self.module3.setCheckable(True)
        self.module3.setAutoExclusive(True)
        self.module3.setFlat(False)
        self.module3.setObjectName("module3")
        self.verticalLayout.addWidget(self.module3)
        self.module4 = QtWidgets.QPushButton(self.moviment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.module4.sizePolicy().hasHeightForWidth())
        self.module4.setSizePolicy(sizePolicy)
        self.module4.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light ")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.module4.setFont(font)
        self.module4.setStyleSheet("")
        self.module4.setCheckable(True)
        self.module4.setAutoExclusive(True)
        self.module4.setObjectName("module4")
        self.verticalLayout.addWidget(self.module4)
        self.module5 = QtWidgets.QPushButton(self.moviment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.module5.sizePolicy().hasHeightForWidth())
        self.module5.setSizePolicy(sizePolicy)
        self.module5.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light ")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.module5.setFont(font)
        self.module5.setStyleSheet("")
        self.module5.setCheckable(True)
        self.module5.setAutoExclusive(True)
        self.module5.setObjectName("module5")
        self.verticalLayout.addWidget(self.module5)
        self.module6 = QtWidgets.QPushButton(self.moviment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.module6.sizePolicy().hasHeightForWidth())
        self.module6.setSizePolicy(sizePolicy)
        self.module6.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light ")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.module6.setFont(font)
        self.module6.setStyleSheet("")
        self.module6.setCheckable(True)
        self.module6.setAutoExclusive(True)
        self.module6.setObjectName("module6")
        self.verticalLayout.addWidget(self.module6)
        self.module7 = QtWidgets.QPushButton(self.moviment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.module7.sizePolicy().hasHeightForWidth())
        self.module7.setSizePolicy(sizePolicy)
        self.module7.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light ")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.module7.setFont(font)
        self.module7.setStyleSheet("")
        self.module7.setCheckable(True)
        self.module7.setAutoExclusive(True)
        self.module7.setObjectName("module7")
        self.verticalLayout.addWidget(self.module7)
        self.modulemix = QtWidgets.QPushButton(self.moviment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modulemix.sizePolicy().hasHeightForWidth())
        self.modulemix.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light ")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.modulemix.setFont(font)
        self.modulemix.setStyleSheet("QPushButton{\n"
"    border-left:10px solid transparent;\n"
"    Text-align:left;\n"
"    \n"
"    background-image: url(:/icons/icons/cil-pencil.png);\n"
"    background-position: center left;\n"
"    background-repeat: none;\n"
"    padding-left: 60px;}")
        self.modulemix.setCheckable(True)
        self.modulemix.setAutoExclusive(True)
        self.modulemix.setObjectName("modulemix")
        self.verticalLayout.addWidget(self.modulemix)
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.moviment)
        spacerItem = QtWidgets.QSpacerItem(47, 247, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_5.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.registro = QtWidgets.QPushButton(self.sfondotasti)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registro.sizePolicy().hasHeightForWidth())
        self.registro.setSizePolicy(sizePolicy)
        self.registro.setMinimumSize(QtCore.QSize(140, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.registro.setFont(font)
        self.registro.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    background-color: rgb(86, 105, 108);\n"
"}\n"
"QPushButton{\n"
"    border-left:5px solid transparent;\n"
"    \n"
"    background-image: url(:/icons/icons/cil-view-column.png);\n"
"    background-position: center left;\n"
"    background-repeat: none;\n"
"    padding-left: 60px;\n"
"Text-align:left;\n"
"    font: 25 16pt \"Microsoft YaHei UI Light 2\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 00px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    border-left-width: 7px;\n"
"    border-style: solid;\n"
"    \n"
"    border-color: rgb(0, 85, 255);\n"
"}")
        self.registro.setCheckable(True)
        self.registro.setAutoExclusive(False)
        self.registro.setObjectName("registro")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.registro)
        self.horizontalLayout_11.addWidget(self.sfondotasti)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setStyleSheet("background-color: rgb(0, 0, 100);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gen = QtWidgets.QStackedWidget(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gen.sizePolicy().hasHeightForWidth())
        self.gen.setSizePolicy(sizePolicy)
        self.gen.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gen.setObjectName("gen")
        self.home = QtWidgets.QWidget()
        self.home.setStyleSheet("")
        self.home.setObjectName("home")
        self.formLayout_4 = QtWidgets.QFormLayout(self.home)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.intro = QtWidgets.QFrame(self.home)
        self.intro.setMinimumSize(QtCore.QSize(0, 0))
        self.intro.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.intro.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.intro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.intro.setObjectName("intro")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.intro)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.AccountFrame = QtWidgets.QFrame(self.intro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AccountFrame.sizePolicy().hasHeightForWidth())
        self.AccountFrame.setSizePolicy(sizePolicy)
        self.AccountFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.AccountFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Arabic")
        font.setPointSize(12)
        self.AccountFrame.setFont(font)
        self.AccountFrame.setStyleSheet("")
        self.AccountFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.AccountFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AccountFrame.setObjectName("AccountFrame")
        self.formLayout_2 = QtWidgets.QFormLayout(self.AccountFrame)
        self.formLayout_2.setVerticalSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.frame_18 = QtWidgets.QFrame(self.AccountFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_18.sizePolicy().hasHeightForWidth())
        self.frame_18.setSizePolicy(sizePolicy)
        self.frame_18.setMinimumSize(QtCore.QSize(0, 31))
        self.frame_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Account = QtWidgets.QLabel(self.frame_18)
        self.Account.setMinimumSize(QtCore.QSize(0, 30))
        self.Account.setMaximumSize(QtCore.QSize(500, 30))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Arabic")
        self.Account.setFont(font)
        self.Account.setStyleSheet("")
        self.Account.setObjectName("Account")
        self.verticalLayout_8.addWidget(self.Account)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.frame_18)
        self.line = QtWidgets.QFrame(self.AccountFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(400, 5))
        self.line.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.line.setSizeIncrement(QtCore.QSize(200, 0))
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.line)
        self.frame_19 = QtWidgets.QFrame(self.AccountFrame)
        self.frame_19.setMinimumSize(QtCore.QSize(35, 35))
        self.frame_19.setMaximumSize(QtCore.QSize(35, 35))
        self.frame_19.setStyleSheet("\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(0, 200, 200);\n"
"    border-radius: 17px;\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(0, 163, 163);\n"
"border-radius: 17px;}")
        self.frame_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_19)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(14, 15))
        self.pushButton_2.setMaximumSize(QtCore.QSize(59, 72))
        self.pushButton_2.setStyleSheet("\n"
"QPushButton{\n"
"\n"
"\n"
"    background-position: center ;\n"
"    background-repeat: none;\n"
"\n"
"\n"
"\n"
"    font: 25 12pt \"Microsoft YaHei UI Light 2\";\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"\n"
"}\n"
"\n"
"QToolTip{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/cil-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(29, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.frame_19)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout_2.setItem(4, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.Nome = QtWidgets.QLabel(self.AccountFrame)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Arabic")
        font.setPointSize(12)
        self.Nome.setFont(font)
        self.Nome.setObjectName("Nome")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Nome)
        self.lineEdit = QtWidgets.QLineEdit(self.AccountFrame)
        self.lineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setFrame(True)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout_2.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.Cognome = QtWidgets.QLabel(self.AccountFrame)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Arabic")
        font.setPointSize(12)
        self.Cognome.setFont(font)
        self.Cognome.setObjectName("Cognome")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.Cognome)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.AccountFrame)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout_2.setItem(8, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        self.MailManager = QtWidgets.QLabel(self.AccountFrame)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Arabic")
        font.setPointSize(12)
        self.MailManager.setFont(font)
        self.MailManager.setObjectName("MailManager")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.MailManager)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.AccountFrame)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout_2.setItem(10, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        self.Cert = QtWidgets.QLabel(self.AccountFrame)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Arabic")
        font.setPointSize(12)
        self.Cert.setFont(font)
        self.Cert.setObjectName("Cert")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.Cert)
        self.comboBox = QtWidgets.QComboBox(self.AccountFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(400, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(720, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout_2.setItem(12, QtWidgets.QFormLayout.LabelRole, spacerItem5)
        self.Moduli = QtWidgets.QLabel(self.AccountFrame)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Arabic")
        font.setPointSize(12)
        self.Moduli.setFont(font)
        self.Moduli.setObjectName("Moduli")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.Moduli)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.AccountFrame)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Arabic")
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setFrame(False)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout_2.setItem(14, QtWidgets.QFormLayout.LabelRole, spacerItem6)
        self.Questions = QtWidgets.QLabel(self.AccountFrame)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Arabic")
        font.setPointSize(12)
        self.Questions.setFont(font)
        self.Questions.setObjectName("Questions")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.Questions)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.AccountFrame)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Arabic")
        font.setPointSize(12)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setText("")
        self.lineEdit_5.setFrame(False)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        spacerItem7 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout_2.setItem(16, QtWidgets.QFormLayout.LabelRole, spacerItem7)
        self.CutScore = QtWidgets.QLabel(self.AccountFrame)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Arabic")
        font.setPointSize(12)
        self.CutScore.setFont(font)
        self.CutScore.setObjectName("CutScore")
        self.formLayout_2.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.CutScore)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.AccountFrame)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Arabic")
        font.setPointSize(12)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setText("")
        self.lineEdit_6.setFrame(False)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout_2.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        spacerItem8 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout_2.setItem(18, QtWidgets.QFormLayout.LabelRole, spacerItem8)
        self.LearningHub = QtWidgets.QLabel(self.AccountFrame)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Arabic")
        font.setPointSize(12)
        self.LearningHub.setFont(font)
        self.LearningHub.setObjectName("LearningHub")
        self.formLayout_2.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.LearningHub)
        self.frame_17 = QtWidgets.QFrame(self.AccountFrame)
        self.frame_17.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_17.setMaximumSize(QtCore.QSize(35, 0))
        self.frame_17.setStyleSheet("background-color: rgb(0, 163, 163);\n"
"border-radius: 17px;")
        self.frame_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.linkbutton = QtWidgets.QPushButton(self.frame_17)
        self.linkbutton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linkbutton.sizePolicy().hasHeightForWidth())
        self.linkbutton.setSizePolicy(sizePolicy)
        self.linkbutton.setMinimumSize(QtCore.QSize(35, 35))
        self.linkbutton.setMaximumSize(QtCore.QSize(35, 35))
        self.linkbutton.setStyleSheet("\n"
"QPushButton{\n"
"\n"
"\n"
"    background-position: center ;\n"
"    background-repeat: none;\n"
"\n"
"\n"
"\n"
"    font: 25 12pt \"Microsoft YaHei UI Light 2\";\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"\n"
"}\n"
"\n"
"QToolTip{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.linkbutton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/cil-arrow-circle-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.linkbutton.setIcon(icon1)
        self.linkbutton.setIconSize(QtCore.QSize(30, 30))
        self.linkbutton.setObjectName("linkbutton")
        self.gridLayout_5.addWidget(self.linkbutton, 0, 0, 1, 1)
        self.formLayout_2.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.frame_17)
        self.Nome.raise_()
        self.Cognome.raise_()
        self.MailManager.raise_()
        self.Cert.raise_()
        self.comboBox.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit.raise_()
        self.line.raise_()
        self.Moduli.raise_()
        self.lineEdit_4.raise_()
        self.Questions.raise_()
        self.lineEdit_5.raise_()
        self.CutScore.raise_()
        self.lineEdit_6.raise_()
        self.LearningHub.raise_()
        self.frame_17.raise_()
        self.frame_18.raise_()
        self.frame_19.raise_()
        self.gridLayout_4.addWidget(self.AccountFrame, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.line_2 = QtWidgets.QFrame(self.intro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 0, 1, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.intro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 400))
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_10.setLineWidth(1)
        self.frame_10.setMidLineWidth(0)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.frame_10)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Arabic")
        self.label_2.setFont(font)
        self.label_2.setToolTip("")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_11.addWidget(self.label_2, 0, QtCore.Qt.AlignLeft)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_10)
        self.scrollArea.setStyleSheet("QScrollBar:vertical {\n"
"            border: 0px solid #999999;\n"
"            background:white;\n"
"            width:10px;    \n"
"            margin: 0px 0px 0px 0px;\n"
"        }\n"
"        QScrollBar::handle:vertical {         \n"
"       \n"
"            min-height: 0px;\n"
"              border: 0px solid red;\n"
"            border-radius: 4px;\n"
"            \n"
"    \n"
"    background-color: rgb(192, 188, 198);\n"
"        }\n"
"        QScrollBar::add-line:vertical {       \n"
"            height: 0px;\n"
"            subcontrol-position: bottom;\n"
"            subcontrol-origin: margin;\n"
"        }\n"
"        QScrollBar::sub-line:vertical {\n"
"            height: 0 px;\n"
"            subcontrol-position: top;\n"
"            subcontrol-origin: margin;\n"
"        }\n"
"QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"background: none;\n"
"}")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 199, 515))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Arabic")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_11.addWidget(self.scrollArea)
        self.gridLayout_4.addWidget(self.frame_10, 0, 2, 1, 1)
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.intro)
        self.gen.addWidget(self.home)
        self.start = QtWidgets.QWidget()
        self.start.setObjectName("start")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.start)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.buttonstart = QtWidgets.QPushButton(self.start)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonstart.sizePolicy().hasHeightForWidth())
        self.buttonstart.setSizePolicy(sizePolicy)
        self.buttonstart.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonstart.setMaximumSize(QtCore.QSize(16777215, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.buttonstart.setFont(font)
        self.buttonstart.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.buttonstart.setObjectName("buttonstart")
        self.verticalLayout_9.addWidget(self.buttonstart, 0, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.start)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Arabic")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.gen.addWidget(self.start)
        self.mostrarisultati = QtWidgets.QWidget()
        self.mostrarisultati.setObjectName("mostrarisultati")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.mostrarisultati)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.mostrarisultati)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 170, 0);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_6 = QtWidgets.QLabel(self.mostrarisultati)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_6.setFont(font)
        self.label_6.setToolTip("")
        self.label_6.setWhatsThis("")
        self.label_6.setStyleSheet("<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">80 </span><span style=\" font-size:16pt; font-weight:600;\">%</span></p></body></html>")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_10.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.tryagain = QtWidgets.QPushButton(self.mostrarisultati)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tryagain.sizePolicy().hasHeightForWidth())
        self.tryagain.setSizePolicy(sizePolicy)
        self.tryagain.setMinimumSize(QtCore.QSize(120, 40))
        self.tryagain.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tryagain.setFont(font)
        self.tryagain.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"\n"
"font: 11pt \"MS Shell Dlg\";\n"
"color: rgb(255, 255, 255);")
        self.tryagain.setObjectName("tryagain")
        self.verticalLayout_10.addWidget(self.tryagain, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.back = QtWidgets.QPushButton(self.mostrarisultati)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back.sizePolicy().hasHeightForWidth())
        self.back.setSizePolicy(sizePolicy)
        self.back.setMinimumSize(QtCore.QSize(120, 40))
        self.back.setMaximumSize(QtCore.QSize(120, 40))
        self.back.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 11pt \"MS Shell Dlg\";\n"
"color: rgb(0, 0, 0);")
        self.back.setObjectName("back")
        self.verticalLayout_10.addWidget(self.back, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gen.addWidget(self.mostrarisultati)
        self.regis = QtWidgets.QWidget()
        self.regis.setObjectName("regis")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.regis)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_15 = QtWidgets.QFrame(self.regis)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 130))
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_12.setContentsMargins(-1, -1, -1, 12)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_3 = QtWidgets.QLabel(self.frame_15)
        self.label_3.setMinimumSize(QtCore.QSize(400, 50))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_12.addWidget(self.label_3)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem9)
        self.frame_12 = QtWidgets.QFrame(self.frame_15)
        self.frame_12.setMinimumSize(QtCore.QSize(120, 40))
        self.frame_12.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_20 = QtWidgets.QFrame(self.frame_12)
        self.frame_20.setMinimumSize(QtCore.QSize(35, 35))
        self.frame_20.setMaximumSize(QtCore.QSize(35, 35))
        self.frame_20.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    background-color: rgb(0, 200, 200);\n"
"    border-radius: 17px;\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(0, 163, 163);\n"
"border-radius: 17px;}")
        self.frame_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_20)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.download = QtWidgets.QPushButton(self.frame_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.download.sizePolicy().hasHeightForWidth())
        self.download.setSizePolicy(sizePolicy)
        self.download.setMinimumSize(QtCore.QSize(35, 35))
        self.download.setMaximumSize(QtCore.QSize(35, 35))
        self.download.setStyleSheet("")
        self.download.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/cil-vertical-align-bottom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.download.setIcon(icon2)
        self.download.setIconSize(QtCore.QSize(20, 20))
        self.download.setObjectName("download")
        self.gridLayout.addWidget(self.download, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.frame_20)
        spacerItem10 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.empty = QtWidgets.QPushButton(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.empty.sizePolicy().hasHeightForWidth())
        self.empty.setSizePolicy(sizePolicy)
        self.empty.setMinimumSize(QtCore.QSize(60, 25))
        self.empty.setMaximumSize(QtCore.QSize(60, 25))
        self.empty.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    background-color: rgb(0, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(0, 163, 163);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.empty.setObjectName("empty")
        self.horizontalLayout_7.addWidget(self.empty)
        self.verticalLayout_12.addWidget(self.frame_12, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.verticalLayout_6.addWidget(self.frame_15)
        self.Tabella = QtWidgets.QTableWidget(self.regis)
        self.Tabella.setStyleSheet("QScrollBar:vertical {\n"
"            border: 0px solid #999999;\n"
"            background:white;\n"
"            width:10px;    \n"
"            margin: 0px 0px 0px 0px;\n"
"        }\n"
"        QScrollBar::handle:vertical {         \n"
"       \n"
"            min-height: 0px;\n"
"              border: 0px solid red;\n"
"            border-radius: 4px;\n"
"            \n"
"    \n"
"    background-color: rgb(192, 188, 198);\n"
"        }\n"
"        QScrollBar::add-line:vertical {       \n"
"            height: 0px;\n"
"            subcontrol-position: bottom;\n"
"            subcontrol-origin: margin;\n"
"        }\n"
"        QScrollBar::sub-line:vertical {\n"
"            height: 0 px;\n"
"            subcontrol-position: top;\n"
"            subcontrol-origin: margin;\n"
"        }\n"
"QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"background: none;\n"
"}")
        self.Tabella.setAlternatingRowColors(True)
        self.Tabella.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.Tabella.setObjectName("Tabella")
        self.Tabella.setColumnCount(5)
        self.Tabella.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Tabella.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabella.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabella.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabella.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabella.setHorizontalHeaderItem(4, item)
        self.verticalLayout_6.addWidget(self.Tabella)
        self.gen.addWidget(self.regis)
        self.page1 = QtWidgets.QWidget()
        self.page1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.page1.setObjectName("page1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame2 = QtWidgets.QFrame(self.page1)
        self.frame2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2.setObjectName("frame2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame1 = QtWidgets.QFrame(self.frame2)
        self.frame1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1.setObjectName("frame1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_11 = QtWidgets.QFrame(self.frame1)
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.titolomodulo = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light 2")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.titolomodulo.setFont(font)
        self.titolomodulo.setStyleSheet("font: 25 18pt \"Microsoft YaHei UI Light 2\";\n"
"")
        self.titolomodulo.setObjectName("titolomodulo")
        self.horizontalLayout_4.addWidget(self.titolomodulo, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.verticalLayout_3.addWidget(self.frame_11)
        self.generale = QtWidgets.QFrame(self.frame1)
        self.generale.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.generale.setFrameShadow(QtWidgets.QFrame.Raised)
        self.generale.setObjectName("generale")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.generale)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.domande = QtWidgets.QFrame(self.generale)
        self.domande.setMaximumSize(QtCore.QSize(16777215, 250))
        self.domande.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.domande.setFrameShadow(QtWidgets.QFrame.Raised)
        self.domande.setObjectName("domande")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.domande)
        self.horizontalLayout_5.setContentsMargins(50, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.domanda = QtWidgets.QLabel(self.domande)
        self.domanda.setStyleSheet("font: 12pt \"MS Shell Dlg\";")
        self.domanda.setText("")
        self.domanda.setWordWrap(True)
        self.domanda.setObjectName("domanda")
        self.horizontalLayout_5.addWidget(self.domanda)
        self.verticalLayout_4.addWidget(self.domande)
        self.risposte = QtWidgets.QFrame(self.generale)
        self.risposte.setStyleSheet("QRadioButton{\n"
"font: 12pt \"MS Shell Dlg\";\n"
"}\n"
"\n"
"QCheckBox{\n"
"font: 12pt \"MS Shell Dlg\";\n"
"}")
        self.risposte.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.risposte.setFrameShadow(QtWidgets.QFrame.Raised)
        self.risposte.setObjectName("risposte")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.risposte)
        self.verticalLayout_2.setContentsMargins(50, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_4.addWidget(self.risposte, 0, QtCore.Qt.AlignTop)
        self.confermafinale = QtWidgets.QFrame(self.generale)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confermafinale.sizePolicy().hasHeightForWidth())
        self.confermafinale.setSizePolicy(sizePolicy)
        self.confermafinale.setMaximumSize(QtCore.QSize(16777215, 30))
        self.confermafinale.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.confermafinale.setFrameShadow(QtWidgets.QFrame.Raised)
        self.confermafinale.setObjectName("confermafinale")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.confermafinale)
        self.horizontalLayout_6.setContentsMargins(50, 0, 20, 0)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.indietro = QtWidgets.QPushButton(self.confermafinale)
        self.indietro.setStyleSheet("background-color: rgb(0, 163, 163);\n"
"color: rgb(255, 255, 255);")
        self.indietro.setObjectName("indietro")
        self.horizontalLayout_6.addWidget(self.indietro)
        self.avanti = QtWidgets.QPushButton(self.confermafinale)
        self.avanti.setStyleSheet("background-color: rgb(0, 163, 163);\n"
"color: rgb(255, 255, 255);")
        self.avanti.setObjectName("avanti")
        self.horizontalLayout_6.addWidget(self.avanti)
        spacerItem11 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.numerodomanda = QtWidgets.QLabel(self.confermafinale)
        self.numerodomanda.setText("")
        self.numerodomanda.setObjectName("numerodomanda")
        self.horizontalLayout_6.addWidget(self.numerodomanda)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.conf = QtWidgets.QPushButton(self.confermafinale)
        self.conf.setStyleSheet("background-color: rgb(0, 163, 163);\n"
"color: rgb(255, 255, 255);")
        self.conf.setObjectName("conf")
        self.horizontalLayout_6.addWidget(self.conf)
        self.verticalLayout_4.addWidget(self.confermafinale)
        self.verticalLayout_3.addWidget(self.generale)
        self.verticalLayout_5.addWidget(self.frame1)
        self.horizontalLayout_3.addWidget(self.frame2)
        self.gen.addWidget(self.page1)
        self.horizontalLayout.addWidget(self.gen)
        self.horizontalLayout_11.addWidget(self.frame_8)
        self.gridLayout_7.addWidget(self.frame_3, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_2.setStyleSheet("QFrame{\n"
"\n"
"    \n"
"    background-color: rgb(61, 59, 73);\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_9.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_4.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(86, 105, 108);\n"
"}\n"
"QPushButton{\n"
"border-radius: 50px;}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_8.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.testbutton = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testbutton.sizePolicy().hasHeightForWidth())
        self.testbutton.setSizePolicy(sizePolicy)
        self.testbutton.setMinimumSize(QtCore.QSize(0, 30))
        self.testbutton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.testbutton.setStyleSheet("")
        self.testbutton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/cil-menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.testbutton.setIcon(icon3)
        self.testbutton.setIconSize(QtCore.QSize(30, 30))
        self.testbutton.setObjectName("testbutton")
        self.gridLayout_8.addWidget(self.testbutton, 2, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setStyleSheet("background-color: rgb(61, 59, 73);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_13 = QtWidgets.QFrame(self.frame_5)
        self.frame_13.setMinimumSize(QtCore.QSize(40, 30))
        self.frame_13.setMaximumSize(QtCore.QSize(40, 30))
        self.frame_13.setStyleSheet("border-image: url(:/icons/iconafinale2.ico);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_8.addWidget(self.frame_13)
        self.label = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Arabic 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 75 20pt \"IBM Plex Arabic 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.horizontalLayout_9.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_6.setStyleSheet("QPushButton:hover{\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(150, 60))
        self.frame_7.setMaximumSize(QtCore.QSize(150, 60))
        self.frame_7.setStyleSheet("QPushButton{\n"
"border-radius: 5px;}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.closebutton = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closebutton.sizePolicy().hasHeightForWidth())
        self.closebutton.setSizePolicy(sizePolicy)
        self.closebutton.setMinimumSize(QtCore.QSize(0, 0))
        self.closebutton.setMaximumSize(QtCore.QSize(70, 70))
        self.closebutton.setStyleSheet("")
        self.closebutton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closebutton.setIcon(icon4)
        self.closebutton.setIconSize(QtCore.QSize(30, 30))
        self.closebutton.setObjectName("closebutton")
        self.gridLayout_9.addWidget(self.closebutton, 0, 3, 1, 1)
        self.minimizebutton = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimizebutton.sizePolicy().hasHeightForWidth())
        self.minimizebutton.setSizePolicy(sizePolicy)
        self.minimizebutton.setMinimumSize(QtCore.QSize(0, 0))
        self.minimizebutton.setMaximumSize(QtCore.QSize(70, 70))
        self.minimizebutton.setStyleSheet("QPushButton:hover{\n"
"\n"
"    background-color: rgb(0, 85, 255);\n"
"    \n"
"}\n"
"QPushButton{\n"
"border-radius:10px;\n"
"}")
        self.minimizebutton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/cil-minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizebutton.setIcon(icon5)
        self.minimizebutton.setIconSize(QtCore.QSize(30, 30))
        self.minimizebutton.setObjectName("minimizebutton")
        self.gridLayout_9.addWidget(self.minimizebutton, 0, 1, 1, 1)
        self.maximizebutton = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maximizebutton.sizePolicy().hasHeightForWidth())
        self.maximizebutton.setSizePolicy(sizePolicy)
        self.maximizebutton.setStyleSheet("QPushButton:hover{\n"
"\n"
"    background-color: rgb(0, 85, 255);\n"
"    \n"
"}")
        self.maximizebutton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/cil-window-restore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximizebutton.setIcon(icon6)
        self.maximizebutton.setIconSize(QtCore.QSize(30, 30))
        self.maximizebutton.setObjectName("maximizebutton")
        self.gridLayout_9.addWidget(self.maximizebutton, 0, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame_7)
        self.pushButton.setMinimumSize(QtCore.QSize(34, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(34, 30))
        self.pushButton.setStyleSheet("QPushButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(170, 0, 255);\n"
"    \n"
"}\n"
"QPushButton{\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    border-radius:10px;\n"
"    background-position: center ;\n"
"    \n"
"    background-repeat: none;\n"
"   \n"
"}")
        self.pushButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/cil-lightbulb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon7)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setAutoRepeat(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_9.addWidget(self.pushButton, 0, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.frame_7)
        self.horizontalLayout_9.addWidget(self.frame_6)
        self.gridLayout_7.addWidget(self.frame_2, 0, 0, 1, 1)
        self.horizontalLayout_13.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.gen.setCurrentIndex(0)
        self.back.clicked.connect(self.module0.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.module0.setText(_translate("MainWindow", "Dashboard"))
        self.moduletest.setText(_translate("MainWindow", "Test"))
        self.module1.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.module1.setText(_translate("MainWindow", " 1    Modulo"))
        self.module2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.module2.setText(_translate("MainWindow", " 2   Modulo"))
        self.module3.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.module3.setText(_translate("MainWindow", " 3   Modulo"))
        self.module4.setText(_translate("MainWindow", " 4   Modulo"))
        self.module5.setText(_translate("MainWindow", " 5   Modulo"))
        self.module6.setText(_translate("MainWindow", " 6   Modulo"))
        self.module7.setText(_translate("MainWindow", " 7   Modulo"))
        self.modulemix.setText(_translate("MainWindow", "Simulazione Esame"))
        self.registro.setText(_translate("MainWindow", "Registro"))
        self.Account.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Account<br/><br/><br/></span></p></body></html>"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI Light 2\'; font-size:12pt; font-weight:24; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">Salva Profilo</span></p></body></html>"))
        self.pushButton_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>PProva</p></body></html>"))
        self.Nome.setText(_translate("MainWindow", "Nome"))
        self.Cognome.setText(_translate("MainWindow", "Cognome"))
        self.MailManager.setText(_translate("MainWindow", "Manager"))
        self.Cert.setText(_translate("MainWindow", "Certificazione"))
        self.comboBox.setItemText(1, _translate("MainWindow", "SAP S4 Hana - C_TS492_1909 Sourcing and Procurement (MM)"))
        self.Moduli.setText(_translate("MainWindow", "Moduli"))
        self.Questions.setText(_translate("MainWindow", "Domande"))
        self.CutScore.setText(_translate("MainWindow", "Cut Score"))
        self.LearningHub.setText(_translate("MainWindow", "Learning Hub"))
        self.linkbutton.setToolTip(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI Light 2\'; font-size:12pt; font-weight:24; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">Apri link</span></p></body></html>"))
        self.linkbutton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Aree Tematiche<br/><br/><br/></span></p></body></html>"))
        self.buttonstart.setText(_translate("MainWindow", "Start"))
        self.label_4.setText(_translate("MainWindow", "Test Cut Score: 80%"))
        self.label_6.setText(_translate("MainWindow", "80 %"))
        self.tryagain.setText(_translate("MainWindow", "Riprova"))
        self.back.setText(_translate("MainWindow", "Dashboard"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Registro Test Precedenti<br/><br/><br/></span></p></body></html>"))
        self.download.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">Esporta registro</span></p></body></html>"))
        self.empty.setText(_translate("MainWindow", "Svuota"))
        self.Tabella.setSortingEnabled(True)
        item = self.Tabella.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.Tabella.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Cognome"))
        item = self.Tabella.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Data"))
        item = self.Tabella.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Test"))
        item = self.Tabella.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Risultato"))
        self.titolomodulo.setText(_translate("MainWindow", "Modulo 1"))
        self.indietro.setText(_translate("MainWindow", "Indietro"))
        self.avanti.setText(_translate("MainWindow", "Avanti"))
        self.conf.setText(_translate("MainWindow", "Conferma"))
        self.label.setText(_translate("MainWindow", " Quiz SAP S/4 Hana"))
        self.pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Guida all\'uso</p></body></html>"))
import group_rc
